"""empty message

Revision ID: f3c39de33fb1
Revises: 
Create Date: 2017-11-04 15:49:36.261000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c39de33fb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_data', sa.Column('downUrl', sa.String(length=20), nullable=True))
    op.add_column('push_data', sa.Column('hwSerial', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_data', 'hwSerial')
    op.drop_column('push_data', 'downUrl')
    # ### end Alembic commands ###
